# Generated by Django 5.2.8 on 2025-11-17 16:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_type', models.CharField(choices=[('STU', 'Student Administrator'), ('EMP', 'School Employee'), ('INS', 'Instructor')], default='EMP', max_length=3, verbose_name='Administrator Type')),
                ('employee_id', models.CharField(blank=True, help_text='Employee ID for non-student admins.', max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(help_text='The primary user account associated with this administrator.', on_delete=django.db.models.deletion.CASCADE, related_name='election_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Election Administrator',
                'verbose_name_plural': 'Election Administrators',
                'ordering': ['user__last_name', 'user__first_name'],
                'permissions': [('can_configure_elections', 'Can create and configure new election events'), ('can_activate_election', 'Can start the voting period'), ('can_close_election', 'Can formally end the voting period'), ('can_manage_voters', 'Can verify voter eligibility and manage voter list'), ('can_access_sensitive_info', 'Can access sensitive voter PII'), ('can_send_notifications', 'Can send election-related notifications to voters'), ('can_manage_candidates', 'Can add, edit, and delete candidates'), ('can_manage_ballots', 'Can design and manage ballot questions/formats'), ('can_view_results_internal', 'Can view internal, unpublished results summary'), ('can_publish_results', 'Can make election results public'), ('can_audit_logs', 'Can view election audit logs for transparency'), ('can_export_data', 'Can export election data for reporting purposes'), ('can_manage_admins', 'Can add or remove other election administrators'), ('can_handle_disputes', 'Can manage election disputes and complaints'), ('can_reset_votes_emergency', 'Can perform emergency vote reset (Requires multi-person approval)')],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.PositiveSmallIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('course', models.CharField(choices=[('BSCS', 'Bachelor of Science in Computer Science'), ('BSIT', 'Bachelor of Science in Information Technology'), ('BSBA', 'Bachelor of Science in Business Administration'), ('BSHM', 'Bachelor of Science in Hospitality Management')], max_length=4)),
                ('section', models.CharField(blank=True, choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D'), ('E', 'Section E')], max_length=1, null=True)),
                ('is_eligible_to_vote', models.BooleanField(default=True)),
                ('has_voted', models.BooleanField(default=False)),
                ('student_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('date_enrolled', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['-year_level', 'course', 'section'],
            },
        ),
    ]
