# Generated by Django 5.2.8 on 2025-11-25 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_studentprofile_has_voted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='VERIFIED', help_text='Verification status for self-registered users', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the profile was verified', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified this student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
