# Generated by Django 5.2.8 on 2025-11-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='ACLC College of Tacloban', max_length=100)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='system/')),
                ('allow_registration', models.BooleanField(default=True, help_text='If disabled, new users cannot register.')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='If enabled, only admins can access the site.')),
                ('singleton_id', models.IntegerField(default=1, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
