# Generated by Django 5.2.8 on 2025-11-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="E.g., '2025 General Student Council Election'", max_length=200, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False, help_text='Manually toggle to activate/deactivate voting system access.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Election Event',
                'verbose_name_plural': 'Election Events',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Partylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_code', models.CharField(help_text='A short acronym or code (e.g., SAP)', max_length=10, unique=True)),
                ('platform', models.TextField(blank=True, help_text='The core objectives or manifesto of the partylist.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Partylist',
                'verbose_name_plural': 'Partylists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text="A brief description of the role's responsibilities.")),
                ('order_on_ballot', models.PositiveSmallIntegerField(unique=True)),
                ('number_of_winners', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Voting Position',
                'verbose_name_plural': 'Voting Positions',
                'ordering': ['order_on_ballot'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, help_text='Upload a campaign photo or poster.', null=True, upload_to='candidates/%Y/%m/%d/')),
                ('biography', models.TextField(blank=True, help_text='A short biography or statement of intent.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval needed before appearing on ballot.')),
                ('student_profile', models.OneToOneField(help_text='The student running for election.', on_delete=django.db.models.deletion.CASCADE, related_name='candidacy', to='accounts.studentprofile')),
                ('election', models.ForeignKey(help_text='The specific election event this candidate is participating in.', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election')),
                ('partylist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='elections.partylist')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='elections.position')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['election', 'position__order_on_ballot', 'partylist__short_code'],
                'unique_together': {('student_profile', 'position', 'election')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voter_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_votes', to='elections.candidate')),
                ('election', models.ForeignKey(help_text='The specific election event this vote belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='elections.election')),
                ('voter', models.ForeignKey(help_text='The authenticated student who cast the ballot.', on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Vote Record',
                'verbose_name_plural': 'Vote Records',
                'ordering': ['-timestamp'],
                'unique_together': {('voter', 'election')},
            },
        ),
    ]
