# Generated by Django 4.2.26 on 2025-11-21 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='position',
            field=models.ForeignKey(help_text='The position this vote is cast for.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='elections.position'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'election', 'position')},
        ),
    ]
