# Generated by Django 5.2.8 on 2025-11-24 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_studentprofile_has_voted_and_more'),
        ('elections', '0002_alter_vote_unique_together_vote_position_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='ballot_id',
            field=models.UUIDField(blank=True, help_text='Random ID linking to the VoterReceipt (for auditing only).', null=True),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter_ip_address',
        ),
        migrations.CreateModel(
            name='VoterReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_id', models.UUIDField(editable=False, unique=True)),
                ('encrypted_choices', models.TextField(help_text='Encrypted record of choices.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voter_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='elections.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Voter Receipt',
                'verbose_name_plural': 'Voter Receipts',
                'ordering': ['-timestamp'],
                'unique_together': {('voter', 'election')},
            },
        ),
    ]
