# Generated by Django 5.2.8 on 2025-11-25 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_alter_vote_unique_together_vote_ballot_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Event title, e.g., 'Campaign Period'", max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField(blank=True, help_text='Optional details about this event.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of events.')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='elections.election')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['order', 'start_time'],
            },
        ),
    ]
